// Centralized mock data -- used by all pages when backend is unavailable

export const mockUniversities = [
  {
    _id: 'uni1',
    name: 'Massachusetts Institute of Technology',
    city: 'Cambridge',
    country: 'United States',
    ranking: { global: 1 },
    images: ['https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80'],
    financials: { tuitionFee: { international: { min: 57986, currency: '$' } } },
    academics: { majors: ['Computer Science', 'Engineering', 'Physics', 'Mathematics'] },
    admissions: { acceptanceRate: 4, requiresIELTS: true, minIELTS: 7.0, minGPA: 3.9 },
    fitScore: 91,
  },
  {
    _id: 'uni2',
    name: 'University of Oxford',
    city: 'Oxford',
    country: 'United Kingdom',
    ranking: { global: 2 },
    images: ['https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=800&q=80'],
    financials: { tuitionFee: { international: { min: 42000, currency: 'GBP' } } },
    academics: { majors: ['Law', 'Medicine', 'Philosophy', 'Economics'] },
    admissions: { acceptanceRate: 17, requiresIELTS: true, minIELTS: 7.5, minGPA: 3.8 },
    fitScore: 87,
  },
  {
    _id: 'uni3',
    name: 'University of Toronto',
    city: 'Toronto',
    country: 'Canada',
    ranking: { global: 21 },
    images: ['https://images.unsplash.com/photo-1571260899304-425eee4c7efc?auto=format&fit=crop&w=800&q=80'],
    financials: { tuitionFee: { international: { min: 35000, currency: 'CA$' } } },
    academics: { majors: ['Business', 'Computer Science', 'Engineering', 'Health Sciences'] },
    admissions: { acceptanceRate: 43, requiresIELTS: true, minIELTS: 6.5, minGPA: 3.5 },
    fitScore: 78,
  },
  {
    _id: 'uni4',
    name: 'ETH Zurich',
    city: 'Zurich',
    country: 'Switzerland',
    ranking: { global: 7 },
    images: ['https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=800&q=80'],
    financials: { tuitionFee: { international: { min: 1500, currency: 'CHF' } } },
    academics: { majors: ['Engineering', 'Architecture', 'Natural Sciences', 'Mathematics'] },
    admissions: { acceptanceRate: 27, requiresIELTS: true, minIELTS: 7.0, minGPA: 3.7 },
    fitScore: 83,
  },
  {
    _id: 'uni5',
    name: 'National University of Singapore',
    city: 'Singapore',
    country: 'Singapore',
    ranking: { global: 8 },
    images: ['https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=800&q=80'],
    financials: { tuitionFee: { international: { min: 17550, currency: 'S$' } } },
    academics: { majors: ['Business', 'Computing', 'Medicine', 'Design'] },
    admissions: { acceptanceRate: 32, requiresIELTS: true, minIELTS: 6.5, minGPA: 3.6 },
    fitScore: 75,
  },
  {
    _id: 'uni6',
    name: 'University of Melbourne',
    city: 'Melbourne',
    country: 'Australia',
    ranking: { global: 33 },
    images: ['https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=800&q=80'],
    financials: { tuitionFee: { international: { min: 36000, currency: 'A$' } } },
    academics: { majors: ['Arts', 'Science', 'Commerce', 'Engineering'] },
    admissions: { acceptanceRate: 70, requiresIELTS: true, minIELTS: 6.5, minGPA: 3.3 },
    fitScore: 69,
  },
];

export const mockScholarships = [
  {
    _id: 'sch1',
    name: 'Chevening Scholarships',
    provider: 'UK Government',
    country: 'United Kingdom',
    amount: 50000,
    type: 'Merit',
    deadline: '2026-11-05',
    description: 'Fully-funded scholarship for outstanding students from eligible countries to study in the UK.',
    criteria: 'Minimum 2 years work experience, strong academic record, leadership qualities.',
    tags: ['Fully Funded', 'Leadership', 'Masters'],
    isMatch: true,
  },
  {
    _id: 'sch2',
    name: 'Fulbright Foreign Student Program',
    provider: 'U.S. Department of State',
    country: 'United States',
    amount: 45000,
    type: 'Merit',
    deadline: '2026-10-15',
    description: 'Prestigious scholarship for international students to pursue graduate study in the USA.',
    criteria: 'Bachelor degree, English proficiency, strong leadership and community involvement.',
    tags: ['Fully Funded', 'Graduate', 'Research'],
    isMatch: true,
  },
  {
    _id: 'sch3',
    name: 'Vanier Canada Graduate Scholarships',
    provider: 'Government of Canada',
    country: 'Canada',
    amount: 50000,
    type: 'Research',
    deadline: '2026-11-01',
    description: 'Designed to attract and retain world-class doctoral students at Canadian universities.',
    criteria: 'PhD program, academic excellence, research potential, leadership.',
    tags: ['PhD', 'Research', 'Canada'],
    isMatch: false,
  },
  {
    _id: 'sch4',
    name: 'Australia Awards Scholarships',
    provider: 'Australian Government',
    country: 'Australia',
    amount: 40000,
    type: 'Need-Based',
    deadline: '2027-04-30',
    description: 'Long-term development awards for citizens from developing countries to undertake study in Australia.',
    criteria: 'Citizen of eligible developing country, relevant work experience, English proficiency.',
    tags: ['Fully Funded', 'Development', 'Undergraduate & Postgraduate'],
    isMatch: false,
  },
  {
    _id: 'sch5',
    name: 'DAAD Scholarships',
    provider: 'German Academic Exchange Service',
    country: 'Germany',
    amount: 12000,
    type: 'Merit',
    deadline: '2026-10-31',
    description: 'Scholarships for international students wishing to pursue postgraduate studies in Germany.',
    criteria: 'Bachelor degree with above-average grades, German language skills preferred.',
    tags: ['Germany', 'Research', 'Postgraduate'],
    isMatch: true,
  },
  {
    _id: 'sch6',
    name: 'Gates Cambridge Scholarship',
    provider: 'Bill & Melinda Gates Foundation',
    country: 'United Kingdom',
    amount: 55000,
    type: 'Merit',
    deadline: '2026-12-01',
    description: 'Full-cost scholarship for outstanding applicants from outside the UK to study at Cambridge.',
    criteria: 'Outstanding intellectual ability, commitment to improving lives, leadership potential.',
    tags: ['Cambridge', 'Fully Funded', 'All Degrees'],
    isMatch: false,
  },
];

export const mockNotifications = [
  {
    _id: 'notif1',
    title: 'Application Deadline Approaching',
    message: 'MIT application deadline is in 14 days. Make sure your SOP and LORs are ready.',
    type: 'Deadline',
    isRead: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    relatedLink: '/application/uni1',
  },
  {
    _id: 'notif2',
    title: 'New Scholarship Match Found',
    message: 'You are eligible for the Chevening Scholarship worth 50,000. Deadline: Nov 5.',
    type: 'Scholarship',
    isRead: false,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    relatedLink: '/scholarships',
  },
  {
    _id: 'notif3',
    title: 'Consultation Session Confirmed',
    message: 'Your session with Dr. Aisha Rahman is confirmed for tomorrow at 2:00 PM.',
    type: 'Booking',
    isRead: false,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    relatedLink: '/consultation',
  },
  {
    _id: 'notif4',
    title: 'Document Checklist Updated',
    message: 'University of Oxford has updated their document requirements. Review your checklist.',
    type: 'Application',
    isRead: true,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    relatedLink: '/application/uni2',
  },
  {
    _id: 'notif5',
    title: 'Fit Score Recalculated',
    message: 'Your fit score for University of Toronto has increased to 78 after profile update.',
    type: 'System',
    isRead: true,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    relatedLink: '/search',
  },
  {
    _id: 'notif6',
    title: 'New Message from Mentor',
    message: 'James Okafor sent you a message: "I reviewed your SOP draft -- great improvement!"',
    type: 'Message',
    isRead: true,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    relatedLink: '/collaboration',
  },
];

export const mockTestimonials = [
  {
    id: 1,
    name: 'Priya Sharma',
    country: 'India',
    university: 'University of Toronto',
    avatar: 'PS',
    color: 'bg-pink-500',
    quote: "PathFinder's fit score completely changed how I approached university selection. I went from being overwhelmed by 200+ options to a focused shortlist of 6 perfect matches.",
    intake: 'Fall 2024',
  },
  {
    id: 2,
    name: 'Ahmed Al-Rashid',
    country: 'Saudi Arabia',
    university: 'ETH Zurich',
    avatar: 'AA',
    color: 'bg-blue-500',
    quote: "The AI essay brainstorming tool helped me craft an SOP that truly reflected my research goals. Got into my dream program with a full scholarship.",
    intake: 'Spring 2024',
  },
  {
    id: 3,
    name: 'Mei Lin Chen',
    country: 'China',
    university: 'University of Oxford',
    avatar: 'MC',
    color: 'bg-purple-500',
    quote: "I used PathFinder to track 5 applications simultaneously. The timeline and checklist features made the whole process stress-free and organized.",
    intake: 'Fall 2024',
  },
];

export const mockStats = [
  { label: 'Universities Listed', value: '1,200+', icon: null },
  { label: 'Students Helped', value: '48,000+', icon: null },
  { label: 'Scholarships Tracked', value: '3,500+', icon: null },
  { label: 'Success Rate', value: '94%', icon: null },
];

export const mockResources = [
  // IELTS
  {
    _id: 'res1', category: 'IELTS', type: 'Video', isPremium: false,
    title: 'IELTS Writing Task 2 -- Band 9 Masterclass',
    description: 'Step-by-step walkthrough of how to structure arguments, use cohesive devices, and achieve a Band 9 in IELTS Writing Task 2.',
    url: 'https://www.youtube.com/watch?v=rPOE6RWFSfg',
    tags: ['Writing', 'Task 2', 'Band 9'],
    duration: '45 min',
  },
  {
    _id: 'res2', category: 'IELTS', type: 'PDF', isPremium: false,
    title: 'IELTS Academic Reading -- 10 Full Practice Tests',
    description: 'Complete set of 10 IELTS Academic Reading practice tests with answer keys and band score estimator.',
    url: 'https://www.ielts.org/about-the-test/sample-test-questions',
    tags: ['Reading', 'Practice Tests', 'Academic'],
    duration: '10 Tests',
  },
  {
    _id: 'res3', category: 'IELTS', type: 'Article', isPremium: false,
    title: 'IELTS Speaking Part 2 -- 50 Sample Cue Cards',
    description: 'Comprehensive list of 50 cue card topics with model answers, vocabulary, and examiner tips for Speaking Part 2.',
    url: 'https://ieltsliz.com/ielts-speaking-part-2/',
    tags: ['Speaking', 'Cue Cards', 'Vocabulary'],
    duration: '25 min read',
  },
  // TOEFL
  {
    _id: 'res4', category: 'TOEFL', type: 'Video', isPremium: false,
    title: 'TOEFL Integrated Writing -- Full Strategy Guide',
    description: 'Learn exactly how to connect the reading and lecture for a perfect TOEFL Integrated Writing response.',
    url: 'https://www.youtube.com/watch?v=RJUKhiGEJZQ',
    tags: ['Writing', 'Integrated', 'Strategy'],
    duration: '38 min',
  },
  {
    _id: 'res5', category: 'TOEFL', type: 'PDF', isPremium: false,
    title: 'TOEFL Official Practice Tests -- ETS',
    description: 'Official ETS TOEFL iBT sample questions covering Reading, Listening, Speaking, and Writing sections.',
    url: 'https://www.ets.org/toefl/test-takers/ibt/prepare/free-practice-test.html',
    tags: ['Official', 'Practice Tests', 'All Sections'],
    duration: '4 Full Tests',
  },
  {
    _id: 'res6', category: 'TOEFL', type: 'Article', isPremium: false,
    title: 'TOEFL Reading Comprehension -- 15 Key Strategies',
    description: 'Proven techniques for TOEFL Reading including inference questions, vocabulary in context, and time management.',
    url: 'https://magoosh.com/toefl/toefl-reading-tips/',
    tags: ['Reading', 'Strategies', 'Time Management'],
    duration: '18 min read',
  },
  // SAT
  {
    _id: 'res7', category: 'SAT', type: 'Video', isPremium: false,
    title: 'Khan Academy SAT Math -- Complete Prep Course',
    description: 'Free full-length SAT Math preparation with 800+ practice problems, video lessons, and personalized practice.',
    url: 'https://www.khanacademy.org/test-prep/sat',
    tags: ['Math', 'Free', 'Official'],
    duration: '40+ hours',
  },
  {
    _id: 'res8', category: 'SAT', type: 'PDF', isPremium: false,
    title: 'SAT Evidence-Based Reading & Writing Guide',
    description: 'Detailed breakdown of SAT EBRW section with 200 practice questions, answer explanations, and vocabulary lists.',
    url: 'https://collegereadiness.collegeboard.org/sat/practice/full-length-practice-tests',
    tags: ['Reading', 'Writing', 'EBRW'],
    duration: '220 pages',
  },
  {
    _id: 'res9', category: 'SAT', type: 'Article', isPremium: true,
    title: 'SAT Essay -- Scoring Rubric & 10 Top Samples',
    description: 'Analyse real SAT essays that scored 8/8/8, understand the rubric deeply, and practise with annotated examples.',
    url: 'https://blog.prepscholar.com/sat-essay-examples',
    tags: ['Essay', 'Writing', 'Rubric'],
    duration: '30 min read',
  },
  // GRE
  {
    _id: 'res10', category: 'GRE', type: 'Video', isPremium: false,
    title: 'GRE Vocabulary -- 1000 High-Frequency Words',
    description: 'Magoosh complete GRE vocabulary series covering the 1000 most frequently tested words with mnemonics and usage.',
    url: 'https://www.youtube.com/playlist?list=PLSjp1UgCM8ItinolAuMlL7O0EYf5HCMjn',
    tags: ['Vocabulary', 'Verbal', 'Flashcards'],
    duration: '6 hours',
  },
  {
    _id: 'res11', category: 'GRE', type: 'PDF', isPremium: false,
    title: 'GRE Analytical Writing -- AWA Perfect Score Guide',
    description: 'Complete guide to scoring 6/6 on GRE AWA: Issue and Argument essay templates, graded samples, and timing tips.',
    url: 'https://www.ets.org/gre/revised_general/prepare/analytical_writing/issue/pool',
    tags: ['AWA', 'Writing', 'Templates'],
    duration: '180 pages',
  },
  {
    _id: 'res12', category: 'GRE', type: 'Article', isPremium: true,
    title: 'GRE Quant -- 50 Shortcut Strategies for 170',
    description: 'Mathematical shortcuts and pattern recognition techniques that let you solve GRE Quantitative questions in under 90 seconds.',
    url: 'https://magoosh.com/gre/gre-math-tips/',
    tags: ['Quant', 'Math', 'Shortcuts'],
    duration: '45 min read',
  },
  // GMAT
  {
    _id: 'res13', category: 'GMAT', type: 'Video', isPremium: false,
    title: 'GMAT Critical Reasoning -- Full Masterclass',
    description: 'Manhattan Prep complete Critical Reasoning video series covering all 11 question types with frameworks and drills.',
    url: 'https://www.youtube.com/watch?v=kvEJpCaHxBc',
    tags: ['Critical Reasoning', 'Verbal', 'Frameworks'],
    duration: '3 hours',
  },
  {
    _id: 'res14', category: 'GMAT', type: 'PDF', isPremium: false,
    title: 'GMAT Official Guide 2024 -- Sample Questions',
    description: 'Official GMAC sample questions across Data Sufficiency, Problem Solving, Critical Reasoning, and Reading Comprehension.',
    url: 'https://www.mba.com/exams/gmat-exam/prepare-for-the-gmat-exam',
    tags: ['Official', 'All Sections', '2024'],
    duration: '320 pages',
  },
  {
    _id: 'res15', category: 'GMAT', type: 'Article', isPremium: false,
    title: 'GMAT Sentence Correction -- 12 Golden Rules',
    description: 'The 12 most tested grammatical concepts on GMAT Sentence Correction, with 60 practice questions and explanations.',
    url: 'https://gmatclub.com/forum/gmat-sentence-correction-sc-134534.html',
    tags: ['Sentence Correction', 'Grammar', 'Verbal'],
    duration: '35 min read',
  },
  // Essay
  {
    _id: 'res16', category: 'Essay', type: 'Video', isPremium: false,
    title: 'How to Write a Winning Common App Essay',
    description: 'Harvard grad admissions counsellor walks through what makes a Common App essay stand out -- real examples included.',
    url: 'https://www.youtube.com/watch?v=bwRfJY-STIA',
    tags: ['Common App', 'Undergraduate', 'Personal Statement'],
    duration: '52 min',
  },
  {
    _id: 'res17', category: 'Essay', type: 'PDF', isPremium: false,
    title: 'SOP Writing Template for STEM Programs',
    description: 'Annotated SOP template for Masters/PhD applicants in STEM with paragraph-by-paragraph guidance and 5 accepted samples.',
    url: 'https://gradcafe.com/advice/statement-of-purpose/',
    tags: ['SOP', 'STEM', 'Masters', 'PhD'],
    duration: '45 pages',
  },
  {
    _id: 'res18', category: 'Essay', type: 'Article', isPremium: true,
    title: '50 Successful College Essay Prompts & Responses',
    description: 'Real essays from students accepted to Ivy League and top-50 universities, annotated by admissions professionals.',
    url: 'https://blog.prepscholar.com/college-essay-examples',
    tags: ['Ivy League', 'Prompts', 'Examples'],
    duration: '1 hour read',
  },
  // Visa
  {
    _id: 'res19', category: 'Visa', type: 'Video', isPremium: false,
    title: 'US F-1 Student Visa -- Full Interview Prep 2024',
    description: 'Ex-US consulate officer explains exactly what visa interviewers look for and how to answer every common question.',
    url: 'https://www.youtube.com/watch?v=Bx3vdl6OORI',
    tags: ['F-1 Visa', 'USA', 'Interview'],
    duration: '1 hour',
  },
  {
    _id: 'res20', category: 'Visa', type: 'PDF', isPremium: false,
    title: 'UK Student Visa (Tier 4) -- Complete Checklist 2024',
    description: 'Step-by-step document checklist for UK Student visa application including CAS, financial evidence, and biometrics.',
    url: 'https://www.gov.uk/student-visa',
    tags: ['UK', 'Tier 4', 'Checklist', '2024'],
    duration: '28 pages',
  },
  {
    _id: 'res21', category: 'Visa', type: 'Article', isPremium: false,
    title: 'Canada Study Permit -- Step-by-Step Application Guide',
    description: 'Complete walkthrough of applying for a Canadian Study Permit online, including proof of funds and acceptance letter.',
    url: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html',
    tags: ['Canada', 'Study Permit', 'Immigration'],
    duration: '20 min read',
  },
];

export const mockShortlist = [
  {
    university: mockUniversities[0],
    fitScore: 91,
    applicationStatus: 'In Progress',
  },
  {
    university: mockUniversities[1],
    fitScore: 87,
    applicationStatus: 'Not Started',
  },
  {
    university: mockUniversities[2],
    fitScore: 78,
    applicationStatus: 'Submitted',
  },
];
